
name: ECS build and push to ECR

on:
  workflow_dispatch:


env:
  AWS_REGION: ap-south-1
  ECR_REGISTRY: 201760452324.dkr.ecr.ap-south-1.amazonaws.com
  ECR_REPOSITORY: jan26-bootcamp-student-portal
  IMAGE_TAG: ${{ github.sha }}
  app_path: week6/app/
  container_name: student-portal
  service: jan26-bootcamp-student-portal-service
  cluster: jan26-bootcamp-student-portal
  task-def-family: student-portal




jobs:
  
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      
      - name: build, tag and push image to ECR
        id: build-image
        working-directory: ${{ env.app_path }}
        run: |
          # Build a docker image
          docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
      
          # Push image to ECR
          docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}

          echo "image=${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}" >> $GITHUB_OUTPUT
        
      - name: download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.task-def-family }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: ${{ env.container_name }}
          image: ${{ steps.build-image.outputs.image }}

      
      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.service }}
          cluster: ${{ env.cluster }}
          wait-for-service-stability: true






